import { ConnectWallet, useAddress, useContract } from "@thirdweb-dev/react";
import { AuctionListing, DirectListing, Marketplace } from "@thirdweb-dev/sdk";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import Listing from "../components/Listing";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const address = useAddress();
  const [listings, setListings] =
    useState<(AuctionListing | DirectListing)[]>();

  const { contract: marketplace, isLoading } = useContract<Marketplace>(
    "0x4639549f85b7E9092a7E962b6752018C210a6c31"
  );

  const fetchListings = async () => {
    if (isLoading) return;
    const listings = await marketplace?.getActiveListings();
    setListings(listings);
  };

  useEffect(() => {
    fetchListings();
  }, [isLoading]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div style={{ width: "200px" }}>
        <ConnectWallet />
      </div>

      {address && (
        <div>
          {listings?.map((listing) => (
            <Listing listing={listing} />
          ))}
        </div>
      )}
    </div>
  );
};

export default Home;
